import { LucideIcon, TrendingUp, TrendingDown, Activity, DollarSign, PieChart, BarChart3 } from "lucide-react";

export interface Stock {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  marketCap: string;
  volume: string;
  peRatio: number;
  sector: string;
  recommendation: "Buy" | "Sell" | "Hold";
  score: number; // 0-100 AI Confidence Score
  technicalSignal: "Bullish" | "Bearish" | "Neutral";
  fundamentalSignal: "Strong" | "Weak" | "Neutral";
  description: string;
}

export const STOCKS: Stock[] = [
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 181.92,
    change: -1.88,
    changePercent: -0.74,
    marketCap: "4.5T",
    volume: "45.2M",
    peRatio: 72.4,
    sector: "Technology",
    recommendation: "Buy",
    score: 94,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "NVIDIA is the leading manufacturer of graphics processing units (GPUs) and AI hardware.",
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    price: 215.98,
    change: 1.58,
    changePercent: 0.74,
    marketCap: "350B",
    volume: "62.1M",
    peRatio: 345.1,
    sector: "Technology",
    recommendation: "Hold",
    score: 65,
    technicalSignal: "Neutral",
    fundamentalSignal: "Strong",
    description: "AMD develops computer processors and related technologies for business and consumer markets.",
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 477.73,
    change: -12.27,
    changePercent: -2.50,
    marketCap: "3.5T",
    volume: "22.5M",
    peRatio: 36.8,
    sector: "Technology",
    recommendation: "Buy",
    score: 88,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Microsoft is a global technology leader known for Windows, Office, and Azure cloud services.",
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    price: 446.74,
    change: 17.50,
    changePercent: 4.08,
    marketCap: "1.4T",
    volume: "98.4M",
    peRatio: 40.2,
    sector: "Consumer Cyclical",
    recommendation: "Sell",
    score: 32,
    technicalSignal: "Bearish",
    fundamentalSignal: "Weak",
    description: "Tesla designs and manufactures electric vehicles, battery energy storage, and solar products.",
  },
  {
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: 316.12,
    change: 3.58,
    changePercent: 1.15,
    marketCap: "858B",
    volume: "8.9M",
    peRatio: 15.6,
    sector: "Financial Services",
    recommendation: "Buy",
    score: 82,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "JPMorgan Chase is one of the largest financial services firms in the world.",
  },
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 225.48,
    change: 2.14,
    changePercent: 0.96,
    marketCap: "3.6T",
    volume: "52.3M",
    peRatio: 33.5,
    sector: "Technology",
    recommendation: "Buy",
    score: 86,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Apple designs and sells consumer electronics, software, and services worldwide.",
  },
  {
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    price: 192.15,
    change: 3.02,
    changePercent: 1.60,
    marketCap: "1.9T",
    volume: "60.4M",
    peRatio: 55.2,
    sector: "Consumer Cyclical",
    recommendation: "Buy",
    score: 84,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Amazon is a global e-commerce and cloud computing leader through AWS.",
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc. (Class A)",
    price: 162.44,
    change: -0.82,
    changePercent: -0.50,
    marketCap: "2.0T",
    volume: "28.7M",
    peRatio: 27.3,
    sector: "Communication Services",
    recommendation: "Buy",
    score: 81,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Alphabet is the parent company of Google, spanning search, ads, and cloud.",
  },
  {
    symbol: "META",
    name: "Meta Platforms, Inc.",
    price: 465.20,
    change: -4.15,
    changePercent: -0.88,
    marketCap: "1.2T",
    volume: "21.5M",
    peRatio: 29.8,
    sector: "Communication Services",
    recommendation: "Hold",
    score: 74,
    technicalSignal: "Neutral",
    fundamentalSignal: "Strong",
    description: "Meta builds products that enable people to connect and share, including Facebook and Instagram.",
  },
  {
    symbol: "AVGO",
    name: "Broadcom Inc.",
    price: 1423.55,
    change: 18.22,
    changePercent: 1.30,
    marketCap: "660B",
    volume: "6.1M",
    peRatio: 52.4,
    sector: "Technology",
    recommendation: "Buy",
    score: 87,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Broadcom designs, develops, and supplies a broad range of semiconductor solutions.",
  },
  {
    symbol: "LLY",
    name: "Eli Lilly and Company",
    price: 978.41,
    change: 12.77,
    changePercent: 1.32,
    marketCap: "927B",
    volume: "3.9M",
    peRatio: 85.1,
    sector: "Healthcare",
    recommendation: "Buy",
    score: 83,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Eli Lilly is a pharmaceutical company with leadership in diabetes and obesity treatments.",
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    price: 116.78,
    change: -0.64,
    changePercent: -0.55,
    marketCap: "465B",
    volume: "14.4M",
    peRatio: 13.8,
    sector: "Energy",
    recommendation: "Hold",
    score: 62,
    technicalSignal: "Neutral",
    fundamentalSignal: "Strong",
    description: "Exxon Mobil explores for and produces crude oil, natural gas, and petroleum products.",
  },
  {
    symbol: "CVX",
    name: "Chevron Corporation",
    price: 148.92,
    change: -1.22,
    changePercent: -0.81,
    marketCap: "280B",
    volume: "9.3M",
    peRatio: 12.4,
    sector: "Energy",
    recommendation: "Hold",
    score: 58,
    technicalSignal: "Neutral",
    fundamentalSignal: "Neutral",
    description: "Chevron engages in integrated energy operations with upstream and downstream segments.",
  },
  {
    symbol: "UNH",
    name: "UnitedHealth Group Incorporated",
    price: 521.36,
    change: 4.45,
    changePercent: 0.86,
    marketCap: "483B",
    volume: "3.2M",
    peRatio: 23.5,
    sector: "Healthcare",
    recommendation: "Buy",
    score: 80,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "UnitedHealth is a diversified healthcare company providing insurance and services.",
  },
  {
    symbol: "V",
    name: "Visa Inc.",
    price: 274.33,
    change: 1.18,
    changePercent: 0.43,
    marketCap: "580B",
    volume: "6.0M",
    peRatio: 30.1,
    sector: "Financial Services",
    recommendation: "Buy",
    score: 79,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Visa operates a global digital payments network connecting consumers, merchants, and banks.",
  },
  {
    symbol: "MA",
    name: "Mastercard Incorporated",
    price: 464.12,
    change: 3.45,
    changePercent: 0.75,
    marketCap: "435B",
    volume: "3.1M",
    peRatio: 37.2,
    sector: "Financial Services",
    recommendation: "Buy",
    score: 78,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "Mastercard provides payment transaction processing and related services globally.",
  },
  {
    symbol: "KO",
    name: "The Coca-Cola Company",
    price: 62.14,
    change: 0.32,
    changePercent: 0.52,
    marketCap: "267B",
    volume: "12.6M",
    peRatio: 24.8,
    sector: "Consumer Defensive",
    recommendation: "Hold",
    score: 65,
    technicalSignal: "Neutral",
    fundamentalSignal: "Strong",
    description: "Coca-Cola produces and sells beverage concentrates and syrups worldwide.",
  },
  {
    symbol: "PEP",
    name: "PepsiCo, Inc.",
    price: 179.88,
    change: 1.05,
    changePercent: 0.59,
    marketCap: "247B",
    volume: "5.8M",
    peRatio: 26.7,
    sector: "Consumer Defensive",
    recommendation: "Hold",
    score: 67,
    technicalSignal: "Neutral",
    fundamentalSignal: "Strong",
    description: "PepsiCo manufactures and sells beverages and convenient foods globally.",
  },
  {
    symbol: "MCD",
    name: "McDonald's Corporation",
    price: 291.77,
    change: 0.88,
    changePercent: 0.30,
    marketCap: "211B",
    volume: "3.4M",
    peRatio: 24.1,
    sector: "Consumer Cyclical",
    recommendation: "Buy",
    score: 72,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "McDonald's operates and franchises quick-service restaurants worldwide.",
  },
  {
    symbol: "DIS",
    name: "The Walt Disney Company",
    price: 118.35,
    change: -0.74,
    changePercent: -0.62,
    marketCap: "216B",
    volume: "8.2M",
    peRatio: 31.4,
    sector: "Communication Services",
    recommendation: "Hold",
    score: 61,
    technicalSignal: "Neutral",
    fundamentalSignal: "Neutral",
    description: "Disney operates media networks, parks, experiences, and consumer products.",
  },
  {
    symbol: "NKE",
    name: "NIKE, Inc.",
    price: 112.44,
    change: 1.18,
    changePercent: 1.06,
    marketCap: "172B",
    volume: "7.9M",
    peRatio: 30.7,
    sector: "Consumer Cyclical",
    recommendation: "Hold",
    score: 63,
    technicalSignal: "Neutral",
    fundamentalSignal: "Neutral",
    description: "Nike designs, develops, and sells athletic footwear, apparel, and equipment.",
  },
  {
    symbol: "BA",
    name: "The Boeing Company",
    price: 209.55,
    change: -2.34,
    changePercent: -1.10,
    marketCap: "127B",
    volume: "6.6M",
    peRatio: 52.9,
    sector: "Industrials",
    recommendation: "Hold",
    score: 55,
    technicalSignal: "Bearish",
    fundamentalSignal: "Neutral",
    description: "Boeing designs, manufactures, and sells airplanes and defense systems.",
  },
  {
    symbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    price: 523.44,
    change: 2.12,
    changePercent: 0.41,
    marketCap: "500B",
    volume: "72.5M",
    peRatio: 23.0,
    sector: "ETF",
    recommendation: "Buy",
    score: 80,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "ETF tracking the S&P 500 index.",
  },
  {
    symbol: "QQQ",
    name: "Invesco QQQ Trust",
    price: 439.28,
    change: 3.25,
    changePercent: 0.75,
    marketCap: "240B",
    volume: "48.1M",
    peRatio: 30.5,
    sector: "ETF",
    recommendation: "Buy",
    score: 82,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "ETF tracking the Nasdaq-100 index.",
  },
  {
    symbol: "DIA",
    name: "SPDR Dow Jones Industrial Average ETF Trust",
    price: 401.12,
    change: 0.78,
    changePercent: 0.19,
    marketCap: "30B",
    volume: "3.7M",
    peRatio: 22.4,
    sector: "ETF",
    recommendation: "Hold",
    score: 70,
    technicalSignal: "Neutral",
    fundamentalSignal: "Strong",
    description: "ETF tracking the Dow Jones Industrial Average.",
  },
  {
    symbol: "IWM",
    name: "iShares Russell 2000 ETF",
    price: 212.66,
    change: -0.45,
    changePercent: -0.21,
    marketCap: "65B",
    volume: "24.0M",
    peRatio: 18.6,
    sector: "ETF",
    recommendation: "Hold",
    score: 65,
    technicalSignal: "Neutral",
    fundamentalSignal: "Neutral",
    description: "ETF tracking the Russell 2000 small-cap index.",
  },
  {
    symbol: "XLK",
    name: "Technology Select Sector SPDR Fund",
    price: 201.44,
    change: 1.66,
    changePercent: 0.83,
    marketCap: "60B",
    volume: "7.5M",
    peRatio: 28.5,
    sector: "ETF",
    recommendation: "Buy",
    score: 78,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "ETF tracking the technology sector of the S&P 500.",
  },
  {
    symbol: "XLF",
    name: "Financial Select Sector SPDR Fund",
    price: 42.35,
    change: 0.22,
    changePercent: 0.52,
    marketCap: "35B",
    volume: "18.3M",
    peRatio: 14.1,
    sector: "ETF",
    recommendation: "Hold",
    score: 68,
    technicalSignal: "Neutral",
    fundamentalSignal: "Strong",
    description: "ETF tracking the financial sector of the S&P 500.",
  },
  {
    symbol: "XLV",
    name: "Health Care Select Sector SPDR Fund",
    price: 156.72,
    change: 0.91,
    changePercent: 0.58,
    marketCap: "35B",
    volume: "8.9M",
    peRatio: 20.4,
    sector: "ETF",
    recommendation: "Buy",
    score: 76,
    technicalSignal: "Bullish",
    fundamentalSignal: "Strong",
    description: "ETF tracking the healthcare sector of the S&P 500.",
  },
  {
    symbol: "XLE",
    name: "Energy Select Sector SPDR Fund",
    price: 88.15,
    change: -0.38,
    changePercent: -0.43,
    marketCap: "36B",
    volume: "14.2M",
    peRatio: 11.7,
    sector: "ETF",
    recommendation: "Hold",
    score: 64,
    technicalSignal: "Neutral",
    fundamentalSignal: "Neutral",
    description: "ETF tracking the energy sector of the S&P 500.",
  },
];

export const MOCK_HISTORY_DATA = Array.from({ length: 30 }, (_, i) => {
  const date = new Date();
  date.setDate(date.getDate() - (29 - i));
  return {
    date: date.toLocaleDateString("en-US", { month: "short", day: "numeric" }),
    price: 180 + Math.random() * 50 - 25 + (i * 2), // Upward trend simulation
    volume: Math.floor(Math.random() * 10000) + 5000,
  };
});

export const PORTFOLIO_ITEMS = [
  { symbol: "NVDA", shares: 10, avgCost: 120.00, currentPrice: 181.92, totalValue: 1819.20, return: 619.20, returnPercent: 51.6 },
  { symbol: "MSFT", shares: 25, avgCost: 380.00, currentPrice: 477.73, totalValue: 11943.25, return: 2443.25, returnPercent: 25.7 },
  { symbol: "TSLA", shares: 50, avgCost: 210.00, currentPrice: 446.74, totalValue: 22337.00, return: 11837.00, returnPercent: 112.7 },
];
